---
language: node_js
node_js:
  - "lts/*"
deploy:
  - provider: script
    script: echo Hello world dev
    # script: env CF_SPACE=dev echo HELLO WORLD $CF_SPACE
    on:
      branch: develop
  - provider: script
    script: echo Hello world test
    # script: env CF_SPACE=dev echo HELLO WORLD $CF_SPACE
    on:
      branch: test

# env:
#   global:
#   - secure: esj3ut+TwKX25QzU1koJyTVIX+x1V55graI65X8LiYXKcOP040VPJ9lIC0HeRs5UViBM0Ur1F93rGdgW2zYVzu5MLZoH7KjpzMcG30x+FDqLChT0JfNcLLtLm/wIhx/OAAmsBxXlvjPp092BeEKd3Jug8d329TxwwK5G5XxAatg=
